const ENTER_KEY_PRESSED = 'ENTER_KEY_PRESSED';
const TAB_KEY_PRESSED = 'TAB_KEY_PRESSED';
const BACKSPACE_KEY_PRESSED = 'BACKSPACE_KEY_PRESSED';
const UP_ARROW_PRESSED = 'UP_ARROW_PRESSED';
const DOWN_ARROW_PRESSED = 'DOWN_ARROW_PRESSED';
const ESC_KEY_PRESSED = 'ESC_KEY_PRESSED';

const TAG_REMOVED = 'TAG_REMOVED';
const TAG_SELECTED = 'TAG_SELECTED';

const TEXT_BOX_CHANGE = 'TEXT_BOX_CHANGE';